# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chopchoprss < Formula
  desc "A fast and simple CLI tool for generating and managing RSS feeds"
  homepage "https://github.com/madeofpendletonwool/chopchoprss"
  version "0.1.1"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/madeofpendletonwool/ChopChopRSS/releases/download/v0.1.1/ChopChopRSS_darwin_amd64.tar.gz"
      sha256 "bc21113ad6e882a18e9f14cbbe54cfcc6930eaa42ad619eb25bfd1792895d6ac"

      def install
        bin.install "chopchoprss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/madeofpendletonwool/ChopChopRSS/releases/download/v0.1.1/ChopChopRSS_darwin_arm64.tar.gz"
      sha256 "2154728f08cf678ccb9dcc68a64fc920eef7bf776f4a1b35869a00fd0579c4f8"

      def install
        bin.install "chopchoprss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/madeofpendletonwool/ChopChopRSS/releases/download/v0.1.1/ChopChopRSS_linux_amd64.tar.gz"
        sha256 "84501f99baf28fa132b0b7f9a58f0e92b66a79755d5cf8a5c7eec96ba3059a75"

        def install
          bin.install "chopchoprss"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/madeofpendletonwool/ChopChopRSS/releases/download/v0.1.1/ChopChopRSS_linux_arm64.tar.gz"
        sha256 "883311d94cc5025f656c0a66c989fe910fc9f06a36fb2b51c1842facb10207fc"

        def install
          bin.install "chopchoprss"
        end
      end
    end
  end

  test do
    system "#{bin}/chopchoprss --version"
  end
end
